name: Auto Generate Draft Release

on:
  push:
    tags:
      - 'v*'          # Triggers only on version tags like v1.0.0
  workflow_dispatch:  # Optional: allow manual run

permissions:
  contents: write      # Required to write release notes

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate release notes
        uses: softprops/action-gh-release@v1
        with:
          draft: true                 # Set to true so you can review before publishing
          generate_release_notes: true
