name: Release Drafter

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags like v1.0.0
  workflow_dispatch:

permissions:
  contents: write  #  Needed to create a draft release

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml  #  Use our custom config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
