# name: Auto Generate Draft Release

# on:
#   push:
#     tags:
#       - 'v*'
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Install GitHub CLI
#         run: sudo apt-get install gh

#       - name: Create draft release with auto notes
#         run: |
#           gh release create "$GITHUB_REF_NAME" --generate-notes --draft
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
